version: '3'
services:
  db:
    image: postgres
    container_name: innova-tasks-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data